### ISSUE TITLE
Empty `email: ` in template causes error

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapseformation#52]
```
  File "/Users/tyu/anaconda3/envs/synapseformation/lib/python3.7/site-packages/synapseclient/client.py", line 2597, in invite_to_team
    raise ValueError("Must specify either 'user' or 'inviteeEmail'")
ValueError: Must specify either 'user' or 'inviteeEmail'
```

**Comment by lopierra** [comment]
UPDATE: For now, deleting the empty `email:` field from each of the teams works.

I attempted to create multiple teams with a single YAML file, but when I run `synapseformation create`, only the first team is created.

Snippet from my YAML file:
```
- name: INCLUDE_X01-DeSmith
  type: Team
  can_public_join: false
  description: DeSmith X01 study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_X01-Hakon
  type: Team
  can_public_join: false
  description: Hakonarson X01 study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_EXcEEDS
  type: Team
  can_public_join: false
  description: EXcEEDS (Fidler) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-Sleep
  type: Team
  can_public_join: false
  description: DS-Sleep (Martin) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-PALS
  type: Team
  can_public_join: false
  description: DS-PALS (Rabin) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_ECODS
  type: Team
  can_public_join: false
  description: ECODS (Esbensen) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-ISP
  type: Team
  can_public_join: false
  description: DS-ISP (Baumer) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-Immune
  type: Team
  can_public_join: false
  description: DS-Immune (Khor) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-Brain
  type: Team
  can_public_join: false
  description: DS-Brain (Korenberg) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_DS-COG-AML
  type: Team
  can_public_join: false
  description: DS-COG-AML (Meshinchi) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
- name: INCLUDE_ADS
  type: Team
  can_public_join: false
  description: ADS (Head) study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
```
