### ISSUE TITLE
Ability to link Teams created in the same template to project acls

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapseformation#53]

**Comment by lopierra** [comment]
I would like to be able to create a Team and then create a Project with that team in the same YAML file, without having to know the team ID. Eg:

```
- name: INCLUDE_test3
  type: Team
  can_public_join: false
  description: test study team
  invitations:
  - message: 
    members:
    - principal_id: 3423548 # lopierra
    - email: 
    
- name: INCLUDE Test3
  type: Project
  acl:
  - principal_id: INCLUDE_test3 [WOULD LIKE TO REFER TO TEAM BY NAME INSTEAD OF ID]
    access_type:
    - READ
    - DOWNLOAD
    - UPDATE
    - CREATE
    - DELETE
    - CHANGE_SETTINGS
    - MODERATE
    - CHANGE_PERMISSIONS
  children:
  - name: Dictionaries and Preliminary Data
    type: Folder
  - name: Clinical Tier 1 Dataset 1
    type: Folder
```
